export enum MimeTypes {
    XLS = 'application/vnd.ms-excel',
    XLSX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    XML = 'text/xml',
    ODS = 'application/vnd.oasis.opendocument.spreadsheet',
    CSV = 'text/plain',
    TMPL = 'text/plain',
    PDF = 'application/pdf',
    PHP = 'application/x-httpd-php',
    JPG = 'image/jpeg',
    PNG = 'image/png',
    GIF = 'image/gif',
    BMP = 'image/bmp',
    TXT = 'text/plain',
    DOC = 'application/msword',
    JS = 'text/js',
    SWF = 'application/x-shockwave-flash',
    MP3 = 'audio/mpeg',
    ZIP = 'application/zip',
    RAR = 'application/rar',
    TAR = 'application/tar',
    ARJ = 'application/arj',
    CAB = 'application/cab',
    HTML = 'text/html',
    HTM = 'text/html',
    DEFAULT = 'application/octet-stream',
    FOLDER = 'application/vnd.google-apps.folder'
}
